openapi: 3.0.3
info:
  title: APIFirst Flask con Validación de Usuarios y JWT
  version: 1.0.0
  description: API con validación automática usando OpenAPI y autenticación JWT

servers:
  - url: http://127.0.0.1:5000
    description: Servidor local de desarrollo

tags:
  - name: Hello
    description: Endpoint básico de prueba
  - name: Users
    description: Operaciones CRUD para usuarios
  - name: Products
    description: Operaciones CRUD para productos
  - name: Auth
    description: Autenticación de usuarios

components:
  schemas:
    Product:
      type: object
      required:
        - name
        - price
        - category
      properties:
        name:
          type: string
          minLength: 2
          maxLength: 40
          example: "Smartphone XYZ"
        description:
          type: string
          maxLength: 500
          example: "Último modelo con pantalla AMOLED y cámara de 108MP"
        price:
          type: number
          minimum: 0
          multipleOf: 0.01
          example: 599.99
        category:
          type: string
          enum:
            - electronics
            - books
            - ropa
            - food
          example: "electronics"
        tags:
          type: array
          minItems: 1
          items:
            type: string
          example: ["tecnología", "mobile", "smartphone"]
        inStock:
          type: boolean
          example: true
        specifications:
          type: object
          additionalProperties:
            type: string
          example:
            processor: "Snapdragon 8 Gen 2"
            ram: "12GB"
            storage: "256GB"
            screen: "6.7 inches"
        ratings:
          type: array
          items:
            type: object
            properties:
              score:
                type: integer
                minimum: 1
                maximum: 5
                example: 5
              comment:
                type: string
                maxLength: 200
                example: "Excelente producto, muy rápido y buena cámara"

    User:
      type: object
      required:
        - username
        - password
        - email
      properties:
        username:
          type: string
          minLength: 3
          maxLength: 50
          example: "juanperez"
        password:
          type: string
          minLength: 6
          format: password
          example: "password123"
        email:
          type: string
          format: email
          example: "juan@ejemplo.com"
        full_name:
          type: string
          minLength: 2
          maxLength: 100
          example: "Juan Pérez"

    LoginRequest:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
          example: "juanperez"
        password:
          type: string
          format: password
          example: "password123"

    Token:
      type: object
      properties:
        access_token:
          type: string
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        token_type:
          type: string
          example: "bearer"

    Error:
      type: object
      properties:
        message:
          type: string
        details:
          type: string

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Ingrese el token JWT en el formato Bearer <token>

security:
  - BearerAuth: []

paths:
  /hello:
    get:
      tags:
        - Hello
      summary: Endpoint de prueba hello world
      operationId: helloWorld
      responses:
        '200':
          description: Respuesta exitosa
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Hello World!"

  /auth/register:
    post:
      tags:
        - Auth
      operationId: registerUser
      summary: Registrar un nuevo usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: Usuario registrado correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  user:
                    $ref: '#/components/schemas/User'
        '400':
          description: Error de validación
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /auth/login:
    post:
      tags:
        - Auth
      operationId: loginUser
      summary: Iniciar sesión y obtener token JWT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Login exitoso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
        '401':
          description: Credenciales inválidas
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /users:
    post:
      tags:
        - Users
      operationId: createUser
      summary: Crear un nuevo usuario
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - age
                - email
              properties:
                name:
                  type: string
                  minLength: 2
                  maxLength: 50
                  example: "Juan Pérez"
                age:
                  type: integer
                  minimum: 18
                  maximum: 100
                  example: 25
                email:
                  type: string
                  format: email
                  example: "juan@ejemplo.com"
      responses:
        '201':
          description: Usuario creado correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  age:
                    type: integer
                  email:
                    type: string
        '400':
          description: Error de validación
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /users/{id}:
    get:
      tags:
        - Users
      operationId: getUserById
      summary: Obtener un usuario por ID
      security: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: ID del usuario
      responses:
        '200':
          description: Usuario encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  age:
                    type: integer
                  email:
                    type: string
        '404':
          description: Usuario no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    post:
      tags:
        - Users
      operationId: updateUser
      summary: Actualizar un usuario existente
      security: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: ID del usuario a actualizar
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  minLength: 2
                  maxLength: 50
                  example: "Juan Pérez Actualizado"
                age:
                  type: integer
                  minimum: 18
                  maximum: 100
                  example: 26
                email:
                  type: string
                  format: email
                  example: "juan.actualizado@ejemplo.com"
      responses:
        '200':
          description: Usuario actualizado correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  age:
                    type: integer
                  email:
                    type: string
        '400':
          description: Error de validación
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Usuario no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /products:
    post:
      tags:
        - Products
      operationId: createProduct
      summary: Crear un nuevo producto
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '201':
          description: Producto creado correctamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '400':
          description: Error de validación
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: No autorizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    get:
      tags:
        - Products
      operationId: getProducts
      summary: Obtener lista de productos
      security: []
      parameters:
        - name: category
          in: query
          required: false
          schema:
            type: string
            enum:
              - electronics
              - books
              - ropa
              - food
          description: Filtrar productos por categoría
        - name: inStock
          in: query
          required: false
          schema:
            type: boolean
          description: Filtrar productos en stock
      responses:
        '200':
          description: Lista de productos obtenida correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'

  /products/{id}:
    get:
      tags:
        - Products
      operationId: getProductById
      summary: Obtener un producto por ID
      security: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: ID del producto
      responses:
        '200':
          description: Producto encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Producto no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    put:
      tags:
        - Products
      operationId: updateProduct
      summary: Actualizar un producto existente
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: ID del producto a actualizar
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '200':
          description: Producto actualizado correctamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '400':
          description: Error de validación
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: No autorizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Producto no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      tags:
        - Products
      operationId: deleteProduct
      summary: Eliminar un producto
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: ID del producto a eliminar
      responses:
        '204':
          description: Producto eliminado correctamente
        '401':
          description: No autorizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Producto no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'