openapi: 3.1.1
info:
  title: APIFirst Example
  description: API First example using Flask and OpenAPI
  version: 1.0.0
  contact:
    name: Developer
    email: developer@example.com

servers:
  - url: http://localhost:5000
    description: Development server

paths:
  /hello:
    get:
      summary: Hello World endpoint
      operationId: getHello
      tags:
        - Hello
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Hello, World!"